#! /bin/sh
# based on a script by Duane Johnson with some simplifications

GIT_DIR=`git rev-parse --git-dir`

# not a valid git repo? leave
if [ $? -ne 0 ] ; then
  exit
fi

# Show various information about this git directory
echo "== Remote URL: "
git remote -v
echo

echo "== Remote Branches: "
git branch -r
echo

echo "== Local Branches:"
git branch
echo

echo "== Configuration (.git/config)"
cat "${GIT_DIR}/config"
echo

echo "== Most Recent Commit"
git --no-pager log --max-count=1
echo

echo "Type 'git log' for more commits, or 'git show' for full commit details."
